//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.05 at 07:02:43 AM PST 
//


package i3po.inf191.xsd;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="item" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="PERSON_HEALTH_TERM" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                 &lt;attribute name="RELATIONSHIP_TYPE" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="SCT_CONCEPT_ID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                 &lt;attribute name="SNOMED_DESCRIPTION" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="code" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                 &lt;attribute name="kndg_code" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *                 &lt;attribute name="kndg_source" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *                 &lt;attribute name="searchpayload" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="title" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="context" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="datasetversion" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="elapsed" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="hardexpiration" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="inception" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="licenseexpiration" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="minversion" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="searchmode" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="searchstring" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="size" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="softexpiration" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="source" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="totalsize" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "item"
})
@XmlRootElement(name = "items", namespace = "")
public class Items {

    @XmlElement(required = true)
    protected List<Items.Item> item;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String context;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String datasetversion;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String elapsed;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String hardexpiration;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String inception;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String licenseexpiration;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String minversion;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String searchmode;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String searchstring;
    @XmlAttribute(required = true)
    protected BigInteger size;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String softexpiration;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String source;
    @XmlAttribute(required = true)
    protected BigInteger totalsize;

    /**
     * Gets the value of the item property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the item property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Items.Item }
     * 
     * 
     */
    public List<Items.Item> getItem() {
        if (item == null) {
            item = new ArrayList<Items.Item>();
        }
        return this.item;
    }

    /**
     * Gets the value of the context property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContext() {
        return context;
    }

    /**
     * Sets the value of the context property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContext(String value) {
        this.context = value;
    }

    /**
     * Gets the value of the datasetversion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatasetversion() {
        return datasetversion;
    }

    /**
     * Sets the value of the datasetversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatasetversion(String value) {
        this.datasetversion = value;
    }

    /**
     * Gets the value of the elapsed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElapsed() {
        return elapsed;
    }

    /**
     * Sets the value of the elapsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElapsed(String value) {
        this.elapsed = value;
    }

    /**
     * Gets the value of the hardexpiration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHardexpiration() {
        return hardexpiration;
    }

    /**
     * Sets the value of the hardexpiration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHardexpiration(String value) {
        this.hardexpiration = value;
    }

    /**
     * Gets the value of the inception property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInception() {
        return inception;
    }

    /**
     * Sets the value of the inception property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInception(String value) {
        this.inception = value;
    }

    /**
     * Gets the value of the licenseexpiration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicenseexpiration() {
        return licenseexpiration;
    }

    /**
     * Sets the value of the licenseexpiration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicenseexpiration(String value) {
        this.licenseexpiration = value;
    }

    /**
     * Gets the value of the minversion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinversion() {
        return minversion;
    }

    /**
     * Sets the value of the minversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinversion(String value) {
        this.minversion = value;
    }

    /**
     * Gets the value of the searchmode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchmode() {
        return searchmode;
    }

    /**
     * Sets the value of the searchmode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchmode(String value) {
        this.searchmode = value;
    }

    /**
     * Gets the value of the searchstring property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchstring() {
        return searchstring;
    }

    /**
     * Sets the value of the searchstring property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchstring(String value) {
        this.searchstring = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSize(BigInteger value) {
        this.size = value;
    }

    /**
     * Gets the value of the softexpiration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoftexpiration() {
        return softexpiration;
    }

    /**
     * Sets the value of the softexpiration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoftexpiration(String value) {
        this.softexpiration = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSource(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the totalsize property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalsize() {
        return totalsize;
    }

    /**
     * Sets the value of the totalsize property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalsize(BigInteger value) {
        this.totalsize = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="PERSON_HEALTH_TERM" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *       &lt;attribute name="RELATIONSHIP_TYPE" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="SCT_CONCEPT_ID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *       &lt;attribute name="SNOMED_DESCRIPTION" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="code" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *       &lt;attribute name="kndg_code" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
     *       &lt;attribute name="kndg_source" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
     *       &lt;attribute name="searchpayload" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="title" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Item {

        @XmlAttribute(name = "PERSON_HEALTH_TERM", required = true)
        protected BigInteger personhealthterm;
        @XmlAttribute(name = "RELATIONSHIP_TYPE", required = true)
        @XmlSchemaType(name = "anySimpleType")
        protected String relationshiptype;
        @XmlAttribute(name = "SCT_CONCEPT_ID", required = true)
        protected BigInteger sctconceptid;
        @XmlAttribute(name = "SNOMED_DESCRIPTION", required = true)
        @XmlSchemaType(name = "anySimpleType")
        protected String snomeddescription;
        @XmlAttribute(required = true)
        protected BigInteger code;
        @XmlAttribute(name = "kndg_code", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "NMTOKEN")
        protected String kndgCode;
        @XmlAttribute(name = "kndg_source", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "NCName")
        protected String kndgSource;
        @XmlAttribute(required = true)
        @XmlSchemaType(name = "anySimpleType")
        protected String searchpayload;
        @XmlAttribute(required = true)
        @XmlSchemaType(name = "anySimpleType")
        protected String title;

        /**
         * Gets the value of the personhealthterm property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getPERSONHEALTHTERM() {
            return personhealthterm;
        }

        /**
         * Sets the value of the personhealthterm property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setPERSONHEALTHTERM(BigInteger value) {
            this.personhealthterm = value;
        }

        /**
         * Gets the value of the relationshiptype property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRELATIONSHIPTYPE() {
            return relationshiptype;
        }

        /**
         * Sets the value of the relationshiptype property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRELATIONSHIPTYPE(String value) {
            this.relationshiptype = value;
        }

        /**
         * Gets the value of the sctconceptid property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getSCTCONCEPTID() {
            return sctconceptid;
        }

        /**
         * Sets the value of the sctconceptid property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setSCTCONCEPTID(BigInteger value) {
            this.sctconceptid = value;
        }

        /**
         * Gets the value of the snomeddescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSNOMEDDESCRIPTION() {
            return snomeddescription;
        }

        /**
         * Sets the value of the snomeddescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSNOMEDDESCRIPTION(String value) {
            this.snomeddescription = value;
        }

        /**
         * Gets the value of the code property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getCode() {
            return code;
        }

        /**
         * Sets the value of the code property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setCode(BigInteger value) {
            this.code = value;
        }

        /**
         * Gets the value of the kndgCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getKndgCode() {
            return kndgCode;
        }

        /**
         * Sets the value of the kndgCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setKndgCode(String value) {
            this.kndgCode = value;
        }

        /**
         * Gets the value of the kndgSource property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getKndgSource() {
            return kndgSource;
        }

        /**
         * Sets the value of the kndgSource property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setKndgSource(String value) {
            this.kndgSource = value;
        }

        /**
         * Gets the value of the searchpayload property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSearchpayload() {
            return searchpayload;
        }

        /**
         * Sets the value of the searchpayload property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSearchpayload(String value) {
            this.searchpayload = value;
        }

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitle(String value) {
            this.title = value;
        }

    }

}
