//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.05 at 07:02:43 AM PST 
//


package i3po.inf191.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.i3po/inf191/xsd/}defRequest"/>
 *         &lt;element ref="{http://www.i3po/inf191/xsd/}defResponse"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "defRequest",
    "defResponse"
})
@XmlRootElement(name = "message_body_example")
public class MessageBodyExample {

    @XmlElement(namespace = "http://www.i3po/inf191/xsd/")
    protected DefRequest defRequest;
    @XmlElement(namespace = "http://www.i3po/inf191/xsd/")
    protected DefResponse defResponse;

    /**
     * Gets the value of the defRequest property.
     * 
     * @return
     *     possible object is
     *     {@link DefRequest }
     *     
     */
    public DefRequest getDefRequest() {
        return defRequest;
    }

    /**
     * Sets the value of the defRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefRequest }
     *     
     */
    public void setDefRequest(DefRequest value) {
        this.defRequest = value;
    }

    /**
     * Gets the value of the defResponse property.
     * 
     * @return
     *     possible object is
     *     {@link DefResponse }
     *     
     */
    public DefResponse getDefResponse() {
        return defResponse;
    }

    /**
     * Sets the value of the defResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefResponse }
     *     
     */
    public void setDefResponse(DefResponse value) {
        this.defResponse = value;
    }

}
