//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.15 at 03:29:28 PM PST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.i3po/inf191/xsd/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package i3po.inf191.xsd;
