//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.05 at 07:02:43 AM PST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.i3po/inf191/xsd/")
package i3po.inf191.xsd;
