//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.07 at 08:57:53 PM PST 
//


package org.i2b2.xsd.cell.def;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.i2b2.org/xsd/cell/def/}definition_request"/>
 *         &lt;element ref="{http://www.i2b2.org/xsd/cell/def/}definition_response"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "definitionRequest",
    "definitionResponse"
})
@XmlRootElement(name = "message_body_example")
public class MessageBodyExample {

    @XmlElement(name = "definition_request")
    protected RequestType definitionRequest;
    @XmlElement(name = "definition_response")
    protected ResponseType definitionResponse;

    /**
     * Gets the value of the definitionRequest property.
     * 
     * @return
     *     possible object is
     *     {@link RequestType }
     *     
     */
    public RequestType getDefinitionRequest() {
        return definitionRequest;
    }

    /**
     * Sets the value of the definitionRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestType }
     *     
     */
    public void setDefinitionRequest(RequestType value) {
        this.definitionRequest = value;
    }

    /**
     * Gets the value of the definitionResponse property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseType }
     *     
     */
    public ResponseType getDefinitionResponse() {
        return definitionResponse;
    }

    /**
     * Sets the value of the definitionResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseType }
     *     
     */
    public void setDefinitionResponse(ResponseType value) {
        this.definitionResponse = value;
    }

}
