//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.07 at 08:57:53 PM PST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.i2b2.org/xsd/cell/def/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.i2b2.xsd.cell.def;
