package i3po.inf191.datavo;

import edu.harvard.i2b2.common.util.jaxb.JAXBUtil;

/**
 * Factory class to create (singleton) jaxb context. Since jaxb context is thread safe, only
 * one instance is created for this cell.
 * 
 * @author rkuttan
 * Modified by Jordaniel Wolk
 */
public class DEFJAXBUtil {
	private static JAXBUtil jaxbUtil = null;

	private DEFJAXBUtil() {
	}

	@SuppressWarnings("unchecked")
	public static JAXBUtil getJAXBUtil() {
		if (jaxbUtil == null) {
			
			// Add strings for packages containing classes generated by xjc. Used to
			// create JAXBContexts of JAXBUtil.
			//TODO make dynamic via Spring/configuration
			String[] jaxbPackageNameArray = {"edu.harvard.i2b2.datavo.i2b2message",
											 "org.i2b2.xsd.cell.def"};
			jaxbUtil = new JAXBUtil(
					jaxbPackageNameArray);
		}

		return jaxbUtil;
	}
}

